# Generated by Django 3.2.9 on 2021-11-24 09:40

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations

import casinorange.home.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "features",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.TextBlock()),
                                ("features", wagtail.core.blocks.ListBlock(casinorange.home.blocks.FeatureBlock)),
                            ]
                        ),
                    ),
                    (
                        "row",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "content",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "content",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "column_size",
                                                            wagtail.core.blocks.ChoiceBlock(
                                                                choices=[
                                                                    ("FULL", "Full width"),
                                                                    ("HALF", "1/2 width"),
                                                                    ("THIRD", "1/3 width"),
                                                                ],
                                                                label="Column size",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "content",
                                                            wagtail.core.blocks.StreamBlock(
                                                                [
                                                                    (
                                                                        "features",
                                                                        wagtail.core.blocks.StructBlock(
                                                                            [
                                                                                (
                                                                                    "title",
                                                                                    wagtail.core.blocks.TextBlock(),
                                                                                ),
                                                                                (
                                                                                    "features",
                                                                                    wagtail.core.blocks.ListBlock(
                                                                                        casinorange.home.blocks.FeatureBlock
                                                                                    ),
                                                                                ),
                                                                            ]
                                                                        ),
                                                                    )
                                                                ],
                                                                label="Content",
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ],
                                        label="Columns",
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
